version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build_windows_latest:
    executor:
      name: win/default
      shell: powershell.exe
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run: npm test
  build_12_18_2:
    docker:
      - image: 'circleci/node:12.18.2'
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run: npm test
  build_latest:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run: npm test
workflows:
  version: 2.1
  workflow:
    jobs:
      - build_12_18_2
      - build_latest
      - build_windows_latest
